# Storage mode: 'yaml' or 'mysql'
storage: yaml

# MySQL configuration (used if storage is set to mysql)
mysql:
  host: localhost
  port: 3306
  database: playervaults
  username: root
  password: password
